# Generated by Django 3.2.4 on 2021-07-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
